package com.xiyuan.mybatis.dao;

import com.xiyuan.mybatis.model.TbTest;
import com.xiyuan.mybatis.model.TbTestExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbTestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test
     *
     * @mbggenerated Thu Aug 11 17:29:02 CST 2016
     */
    int countByExample(TbTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test
     *
     * @mbggenerated Thu Aug 11 17:29:02 CST 2016
     */
    int deleteByExample(TbTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test
     *
     * @mbggenerated Thu Aug 11 17:29:02 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test
     *
     * @mbggenerated Thu Aug 11 17:29:02 CST 2016
     */
    int insert(TbTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test
     *
     * @mbggenerated Thu Aug 11 17:29:02 CST 2016
     */
    int insertSelective(TbTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test
     *
     * @mbggenerated Thu Aug 11 17:29:02 CST 2016
     */
    List<TbTest> selectByExample(TbTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test
     *
     * @mbggenerated Thu Aug 11 17:29:02 CST 2016
     */
    TbTest selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test
     *
     * @mbggenerated Thu Aug 11 17:29:02 CST 2016
     */
    int updateByExampleSelective(@Param("record") TbTest record, @Param("example") TbTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test
     *
     * @mbggenerated Thu Aug 11 17:29:02 CST 2016
     */
    int updateByExample(@Param("record") TbTest record, @Param("example") TbTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test
     *
     * @mbggenerated Thu Aug 11 17:29:02 CST 2016
     */
    int updateByPrimaryKeySelective(TbTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test
     *
     * @mbggenerated Thu Aug 11 17:29:02 CST 2016
     */
    int updateByPrimaryKey(TbTest record);
}